version: '3.7'

services:
  express:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src/:/scripts/
      - node_modules:/scripts/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: